# Generated by Django 4.0.5 on 2023-04-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='logo',
            field=models.FileField(default='logo.png', upload_to='images/logos'),
        ),
    ]
