# Generated by Django 4.0.5 on 2023-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_cliente_empresa_alter_empresa_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Corporacion')),
            ],
        ),
    ]
